apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: files.resources.weisnix.org
spec:
  group: resources.weisnix.org
  names:
    kind: File
    listKind: FileList
    plural: files
    singular: file
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Status
      type: string
      description: Resource status
      JSONPath: .status.status_string
    - name: Host
      type: string
      description: Target host
      JSONPath: .spec.host
    - name: Path
      type: string
      description: File path
      JSONPath: .spec.path
