apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: filecontent.resources.weisnix.org
spec:
  group: resources.weisnix.org
  names:
    kind: FileContent
    listKind: FileContentList
    plural: filecontent
    singular: filecontent
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Status
      type: string
      description: Resource status
      JSONPath: .status.status_string
    - name: Host
      type: string
      description: Target host
      JSONPath: .spec.host
    - name: Path
      type: string
      description: File path
      JSONPath: .spec.path
