apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: commands.resources.weisnix.org
spec:
  group: resources.weisnix.org
  names:
    kind: Command
    listKind: CommandList
    plural: commands
    singular: command
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Status
      type: string
      description: Resource status
      JSONPath: .status.status_string
    - name: Host
      type: string
      description: Target host
      JSONPath: .spec.host
    - name: Command
      type: string
      description: Remote command
      JSONPath: .spec.command
