apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: files.resources.weisnix.org
spec:
  group: resources.weisnix.org
  names:
    kind: File
    listKind: FileList
    plural: files
    singular: file
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
