apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: filecontents.resources.weisnix.org
spec:
  group: resources.weisnix.org
  names:
    kind: FileContents
    listKind: FileContentsList
    plural: filecontents
    singular: filecontents
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
