apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: commands.resources.weisnix.org
spec:
  group: resources.weisnix.org
  names:
    kind: Command
    listKind: CommandList
    plural: commands
    singular: command
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
