apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-ctlr
spec:
  replicas: 1
  selector:
    matchLabels:
      name: resource-ctlr
  template:
    metadata:
      labels:
        name: resource-ctlr
    spec:
      serviceAccountName: resource-ctlr
      containers:
        - name: resource-ctlr
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - resource-ctlr
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "resource-ctlr"
